### ISSUE TITLE
로그인 테스트

### ISSUE THREAD

**Issue by woohyeoung** [woohyeoung/springboot#2]
---
name: 유저 관리
about: 회원 가입, 로그인, 로그아웃

---

## 💡 Issue
테스트 코드를 사용
유저의 회원 가입 작동 여부 확인
회원 가입 이후 로그인 시 토큰 발급 확인
토큰 발급 시 토큰 검증 확인
토큰 만료 시 리프레쉬 토큰을 사용하여 재발급 확인
로그아웃 시 토큰 삭제 확인

## 📝 todo
- [x] 회원가입
- [x] 로그인 시 토큰 발급
- [x] 토큰 검증
- [x] 토큰 만료 시 재발급
- [x] 로그아웃 시 토큰 삭제
